variables:
  services:
    gsearch:
      API: ""
      CSE: ""

processing:
  convert:
    txt:
      type: TextDocument
    pdf:
      type: PDFDocument
    py:
      type: TextDocument
    pptx:
      type: PowerPointDocument
    imageboard_thread:
      type: ImageBoardThreadDocument
    url:
      type: WebDocument
    DEF:
      type: DEFDocument
      
  chunking_strategy:
    txt:
      strategy: tokens
      kwargs:
        max_tokens: 2048
        pattern: " "
    pdf:
      strategy: tokens
      kwargs:
        max_tokens: 512
        pattern: ""
    py:
      strategy: tokens
      kwargs:
        max_tokens: 512
        pattern: ""
    pptx:
      strategy: pattern
      kwargs:
        max_tokens: 512
        pattern: "\n----------\n"
    imageboard_thread:
      strategy: pattern
      kwargs:
        pattern: "------------"
    url:
      strategy: tokens
      kwargs:
        max_tokens: 512
        pattern: ""

    DEF:
      strategy: pattern
      kwargs:
        max_tokens: 512
        pattern: "\n----------\n"


  chunks_post_processing:
    txt:
      strategy: default
      kwargs:
        model_path: {}
    pdf:
      strategy: default
      kwargs: {}
    py:
      strategy: default
      kwargs: {}
    pptx:
      strategy: default
      kwargs: {}
    imageboard_thread:
      strategy: default
      kwargs: {}
    url:
      strategy: default
      kwargs:
        model_path: {}
    DEF:
      strategy: default
      kwargs:
        model_path: {}

engine:
  too_many_tokens_strategy: summarize_chunks
  
logs:
  autosave: true
  save_path: "./logs"